---
extends:
  airbnb

env:
  browser: true
  node: true
  es6: true
  mocha: true
  jquery: true

parser: "babel-eslint"

plugins:
  - babel

ecmaFeatures:
  generators: true,

# 0: off, 1: warning, 2: error
rules:
  # single quotes
  quotes: [2, "single"]
  jsx-quotes: [2, "prefer-single"]
  # 2 space indentation
  indent: [2, 2]
  # Allow _function/variable names (to show privateness)
  no-underscore-dangle: 0
  # Commas always at the end of line
  comma-style: [2, "last"]
  comma-dangle: ["error", {
    "arrays": "only-multiline",
    "objects": "only-multiline",
    "imports": "only-multiline",
    "exports": "only-multiline",
    "functions": "ignore",
  }]
  # 80 char line length
  max-len: [2, 80, 1]
  # console is fine
  no-console: 0

  # returning JSON from arrow functions without a return statement breaks the
  # parser, and having a single return statement is not allowed by this rule...
  arrow-body-style: 0
  new-cap: 0

  react/jsx-closing-bracket-location: 1
  react/jsx-curly-spacing: 2
  react/jsx-indent-props: [2, 2]
  react/jsx-no-duplicate-props: 2
  react/no-danger: 2
  react/no-direct-mutation-state: 1
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"

  quote-props: 0
  generator-star-spacing: 0
  babel/generator-star-spacing: 0
  func-name-matching: 0
  no-confusing-arrow: 0
  react/forbid-prop-types: 0

  # import/no-unresolved: 0 # deps are only installed in the docker container
